# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  xcode-10_3:
    # The type of runner that the job will run on
    runs-on: macOS-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Test with Xcode 10.3
        run: ./xcode_test.sh Xcode_10.3

  xcode-11_0:
    runs-on: macOS-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Test with Xcode 11.0
        run: ./xcode_test.sh Xcode_11

  xcode-11_1:
    runs-on: macOS-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Test with Xcode 11.1
        run: ./xcode_test.sh Xcode_11.1

  xcode-11_2:
    runs-on: macOS-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Test with Xcode 11.2
        run: ./xcode_test.sh Xcode_11.2.1

  xcode-11_3:
    runs-on: macOS-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Test with Xcode 11.3
        run: ./xcode_test.sh Xcode_11.3.1

  xcode-11_4:
    runs-on: macOS-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Test with Xcode 11.4
        run: ./xcode_test.sh Xcode_11.4.1
