#if !canImport(ObjectiveC)
import XCTest

extension OLEKitTests {
  // DO NOT MODIFY: This is autogenerated, use:
  //   `swift test --generate-linuxmain`
  // to regenerate.
  static let __allTests__OLEKitTests = [
    ("testIsOLENegative", testIsOLENegative),
    ("testISOLEPositive", testISOLEPositive),
  ]
}

public func __allTests() -> [XCTestCaseEntry] {
  return [
    testCase(OLEKitTests.__allTests__OLEKitTests),
  ]
}
#endif
