# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the `main` branch
on:
  push:
    branches: [main]
  pull_request:
    branches: "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  macos_build:
    strategy:
      matrix:
        include:
          - xcode: "11.7" # Swift 5.2
            macOS: "10.15"
            useCodecov: "false"
          - xcode: "12.4" # Swift 5.3
            macOS: "10.15"
          - xcode: "12.5.1" # Swift 5.4
            macOS: "11.0"
          - xcode: "13.1" # Swift 5.5
            macOS: "11.0"
          - xcode: "13.4.1" # Swift 5.6
            macOS: "12"

    runs-on: macos-${{ matrix.macOS }}
    name: Build with Xcode ${{ matrix.xcode }} on macOS ${{ matrix.macOS }}

    steps:
      - uses: actions/checkout@v2

      - name: Build with Xcode ${{ matrix.xcode }}
        run: ./xcode_test.sh Xcode_${{ matrix.xcode }}

  linux_build:
    strategy:
      matrix:
        swift:
          - "5.1"
          - "5.2"
          - "5.3"
          - "5.4"
          - "5.5"
          - "5.6"

    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test --enable-test-discovery

  windows_build:
    strategy:
      matrix:
        swift:
          - "5.5"
          - "5.6"

    runs-on: windows-2019

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - uses: MaxDesiatov/swift-windows-action@v1
        with:
          shell-action: swift build
          swift-version: ${{ matrix.swift }}
      - name: Run tests
        run: swift test --enable-test-discovery
