# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the `main` branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  xcode-11_2:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test with Xcode 11.2
        run: ./xcode_test.sh Xcode_11.2.1

  xcode-11_3:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test with Xcode 11.3
        run: ./xcode_test.sh Xcode_11.3.1

  xcode-11_4:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test with Xcode 11.4
        run: ./xcode_test.sh Xcode_11.4.1

  xcode-11_5:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test with Xcode 11.5
        run: ./xcode_test.sh Xcode_11.5

  xcode-11_6:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test with Xcode 11.6
        run: ./xcode_test.sh Xcode_11.6

  xcode-11_7:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test with Xcode 11.7
        run: ./xcode_test.sh Xcode_11.7

  xcode-12_0:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test with Xcode 12.0
        run: ./xcode_test.sh Xcode_12

  linux-5_1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test on Linux with Swift 5.1
        uses: Didstopia/SwiftAction@v1.0.1
        with:
          swift-action: test --enable-test-discovery

  linux-5_2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test on Linux with Swift 5.2
        uses: Didstopia/SwiftAction@v1.0.2
        with:
          swift-action: test --enable-test-discovery

  linux-5_3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test on Linux with Swift 5.3
        uses: Didstopia/SwiftAction@v1.0.3
        with:
          swift-action: test --enable-test-discovery
